### ISSUE TITLE
Use remote configuration

### ISSUE THREAD

**Issue by dberzano** [mconcas/plancton#1]
Find a way to fetch the configuration from, say, a remote HTTP URL. Maybe, HTTPS is better, but bear in mind that the CA must be known. So, in that case, better keeping the configuration on GitHub (it's even versioned then) than on one of the University servers (as long as no sensitive data is contained).

**Comment by mconcas** [comment]
We opted for local configurations updated regularly. Configuration repository is here: https://github.com/mconcas/voluntary-config
