### ISSUE TITLE
Make sure latest version of container is used

### ISSUE THREAD

**Issue by dberzano** [mconcas/plancton#5]
If you adopt the naming schema for containers:

```
mconcas/slc6-container:v1
mconcas/slc6-container:v2
mconcas/slc6-container:latest
```

where `latest` always points to the latest version, you can tell Docker to run `mconcas/slc6-container:latest`.

If the container does not exist, with the current implementation, it is silently pulled. However, no check is performed to make sure that the intended latest version is used.

To do that with the command line you'd do:

```
docker pull mconcas/slc6-container:latest
docker run mconcas/slc6-container:latest [opts...]
```

The `docker pull` part downloads nothing if the latest version is there already, but at least it ensures you are using that one.

The exercise is to implement it via the REST API if possible, like you have done with the rest.

**Comment by mconcas** [comment]
Done.
