### ISSUE TITLE
Show container health in the container table

### ISSUE THREAD

**Issue by mconcas** [mconcas/plancton#57]

**Comment by mconcas** [comment]
With 

```
curl --unix-socket /var/run/docker.sock http:/containers/<containerid>/changes HTTP/1.1
```

one can verify if the filesystem is changed. Why don't we rise a flag (dummy file) somewhere using a wrapper, for example, in order to know if there are running jobs on a given container?

**Comment by dberzano** [comment]
Reporting the decision we've made in person:
- this call is definitely too heavy (and too dependent on recent versions of Docker) when too many files change
- we can think of letting the container write something in some dummy directory which is also mounted outside the container and monitored by Plancton

Note that the last option is actually a "health check" no different than the `/health` HTTP call on many modern applications.

**Comment by mconcas** [comment]
Nowadays it is a builtin feature for docker containers.
