### ISSUE TITLE
Configurable policy for spawning containers by looking at host used resources

### ISSUE THREAD

**Issue by dberzano** [mconcas/plancton#6]
We need to have a plan for that. Some policy that includes a configurable, say, "mathematical formula" or "Python expression" that calculates the number of containers to be spawned.

You might periodically save a series of parameters. For instance:
- disk usage
- load
- CPU usage

and save also an "averaged" version of them over a period of time (5 minutes, 30 minutes, one hour, 12 hours, 1 day).

Decisions can be taken according to this values.

**Note:** this is just a plan, we need a draft to discuss before implementing anything.

**Comment by mconcas** [comment]
We have reached a kind of compromise between policies+monitoring of resources and usability.
