### ISSUE TITLE
Nameless containers make Plancton crash

### ISSUE THREAD

**Issue by mconcas** [mconcas/plancton#67]
Due to some unknown reasons docker spawns nameless container instead the `plancton-slave-XXXXX` ones. Therefore Plancton crashes in accessing those `NoneType` keys.

`TypeError: 'NoneType' object is unsubscriptable
2016-09-21 07:23:39 plancton CRITICAL [daemon.start] Terminating abnormally...`

**Comment by dberzano** [comment]
Fixed in #71.
