### ISSUE TITLE
Drain containers on specific host in a Plancton-based cluster

### ISSUE THREAD

**Issue by mconcas** [mconcas/plancton#78]
Approaches:
 - Periodically check for a file in a specific path
 - ?

**Comment by dberzano** [comment]
I would do:
- `planctonctl drain` to create a "placeholder file" under a certain path (_i.e._ `/var/run/plancton/drain`)
- The presence of this file is checked in the main loop
- `planctonctl start` in addition to what it does now it deletes this file if present

We only add one command (`drain`) and we have some sort of API, so the day we want to use something smarter than "a file" we can do that without changing the interface.

**Comment by dberzano** [comment]
On a second thought: we might need to preserve the drain status upon restarts (use case: live update of Plancton, which involves a `stop`, update and a `start`). I would add an `undrain` command then and leave the `start` command alone.

**Comment by dberzano** [comment]
#87 still misses InfluxDB report of Plancton status (_i.e._ "active" or "draining").

**Comment by mconcas** [comment]
This has been added in #77.
In addition I would like to send the `exited` status, upon stopping the daemon.
