### ISSUE TITLE
Behaviour to assume in case of an exception in talking with InfluxDB database

### ISSUE THREAD

**Issue by mconcas** [mconcas/plancton#81]
### Question:
Basically we have to decide how to manage the `requests.exceptions.ConnectionError` that may rise in feeding a database.

### Description:
There are two cases in which this may occur:

1. Plancton attempts to create a database during its `self.init()` phase. This is done once a startup time.
2. Plancton periodically sends data to the configured  `host:port`. 

### My idea:
Plancton should fail to start in case we decide that the reachability of the database is a necessary condition to run (yet another flag to set this, or a force design choice).
Plancton should be tolerant enough in case the service becomes unreachable for some time or forever. In case of an address changing we might want to be able to reconfigure Plancton to feed the correct new one, this is a second-order enhancement, IMHO.

**Comment by dberzano** [comment]
Here's what I think.
- Plancton should never fail, neither at start nor at runtime.
- Database creation should done lazily, _i.e._ not during `init()` but during each send.
- The first successful creation sets to `True` a variable to prevent useless further creations.

**Comment by dberzano** [comment]
From the conversation we've had, let me add:
- If subsequent sends fail, then the flag is reset to `False`

Up to you to decide whether you want to retry or not (I would not retry).

**Comment by dberzano** [comment]
Fixed by #86.
